[package]
name = "tankgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irrgarten = "0.1.1"
wfc = "0.10.6"
gdnative = "0.11.0"
lazy_static = "*"
rand = "*"

[lib]
crate-type = ["cdylib", "lib"]